### ISSUE TITLE
Can I process compressed file in chunks?

### ISSUE THREAD

**Issue by ebadta81** [gyscos/zstd-rs#168]
Hello,

I am trying to process data from zst archive, but for once, only about 64KB or 124KB of it.

Is it possible?

I tried it with this code:

```
let file = fs::File::open(path).unwrap();
cur.zstd_reader = Some(BufReader::new(file));
	let mut buffer = [0u8; 131072];
	let reader = cur.zstd_reader.as_mut().unwrap();
	reader.read_exact(&mut buffer);
	reader.buffer();

let mut decoder = zstd::Decoder::new(&buffer[..]).unwrap().single_frame();
let mut decoded = Vec::with_capacity(13107200);
decoder.read(&mut decoded).unwrap();
```

but decoder.read always  says: error: "Destination buffer is too small", no matter what i put in the with_capacity() arguments.

My plan is to open many zst files together, and only read and process a little chunk of them at the same time (in a while cycle).

Is this possible?

How can I achieve this?

**Comment by gyscos** [comment]
Hi, and thanks for the question!

### Buffer too small

On your last line:
```rust
decoder.read(&mut decoded).unwrap()
```

This is the [`Read::read(&mut self, buf: &mut [u8]) -> io::Result<usize>`](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) method. It takes `&mut [u8]` as argument.

When you use `&mut decoded`, you use the `DerefMut` implementation of `Vec`, which returns a slice to the valid part of the `Vec`. But [`Vec::with_capacity`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity) returns an _empty_ `Vec` (albeit with the given _capacity_). So `&mut decoded` returns an empty slice. From there, it makes sense that attempting to write there returns "destination buffer too small".

To use a vector as a buffer, you will need to initialize it, for instance with zeros: `let mut decoded = vec![0u8; 13107200];`.

There is no current method that I know of to soundly avoid initializing the `Vec` before giving it to `Read::read`.

(If this "technically un-necessary" zeroing of the buffer is really a performance concern, you will need to give up the `Read` interface; the `zstd-safe` crate uses a `WriteBuf` trait that lets you use `Vec<u8>` with proper capacities as buffers without having to zero their content, but it's not as friendly to use.)

### Reading in chunks

It is _possible_ to only read some chunk of a compressed file, but:
* The `Decoder` needs to see the entire stream from the start (you cannot start with a chunk in the middle of the file).
* If you read enough from the `Decoder` that it reaches the end of the given compressed chunk, but it's not an actual end of zstd frame, it will think the stream is corrupted and return an error.
* There is not much guarantee on how much work it will be to decompress this chunk, or how much data will be produced.

As a result, it may be simpler to instead, have a bunch of Decoders, and _read_ (decompressed) chunks from them, rather than _feeding_ them (compressed) chunks. This would save you a lot of trouble, while still letting you control the progress of each stream.

The pull-based `Read` interface in general is not very well suited to "only feeding input by chunks". You may prefer the `Write` interface (`zstd::stream::write::Decoder`), which is push-based: you explicitly feed compressed chunks to the Decoder, which then writes the decompressed data to a wrapped `Write` (maybe a `Vec<u8>` buffer!).

An alternative is to not use the `Read`/`Write` interface at all, but instead to use `zstd_safe` directly. It's not as documented as the top-level zstd crate, but you will need to:
* Create a [`zstd_safe::CCtx`](https://docs.rs/zstd-safe/latest/zstd_safe/struct.CCtx.html) (compression context)
* Initialize it with `CCtx::init()`.
* Read your compressed chunks, and feed them to `CCtx::compress_stream`.

As a bonus, you would not need to initialize your buffer.

You can see how `zstd` uses `zstd_safe`, or ask more questions here if that's the path you want to take.

Also some minor remarks:
* There is no point in using a `BufReader` if you just call `read_exact` on it - `BufReader` is useful when you need to call `read` many times with small buffers, but only want a few large "actual read" (system calls). If you want to read everything in a single `read`/`read_exact`/`read_to_end`/`read_to_string`, `BufRead` does not bring anything.
* `decoder.read(&mut decoded).unwrap()` does not guarantee that all the chunk given to the decoder is actually processed. You will need to use `read_to_end` or something similar for that.

**Comment by ebadta81** [comment]
Thank you [Alexandre](https://github.com/gyscos), for your quick and detailed answer.

I choose to use your zstd_safe solution.

Everything is okay, but CCtx::compress_stream doesn't makes any changes in OutBuffer, but it processes the input buffer, because I see in it, the pos variable is updated.


Nevertheless, I need decompression, not compression, so I switched to DCtx, and now everything is fine.
I can get and process my data, and also get the pos values in InBuffer and OutBuffer.

Can You confirm, that the pos values are the positions, until the encoder did process the data?
So pos of InBuffer shows me the offset I need, for the next read from the zst file?

Your answer was very much helping me. Have a nice year [Alexandre](https://github.com/gyscos)!

**Comment by gyscos** [comment]
> I choose to use your zstd_safe solution.

A challenge, but it'll certainly give you the most flexibility.
(From the 3 solutions I mentioned, the "zstd::stream::write::Decoder" based approach is probably the closer to your initial example.)

> Nevertheless, I need decompression, not compression

Ah right I got that wrong. `DCtx` it is.

In general `zstd_safe` is very close to the C API, so you can read the great documentation in [`zstd.h`](https://github.com/facebook/zstd/blob/dev/lib/zstd.h) for how to use it.

In particular, the `pos` indexes in `InBuffer` and `OutBuffer` mark the end of the data "processed" (read for `InBuffer`, written for `OutBuffer`) _within the buffer itself_ (not within the entire file). If any data has been consumed like this, it doesn't need to be given again (but any data _after_ `pos` still has not be consumed yet).

You can see how the top-level `zstd` crate wraps these here: https://github.com/gyscos/zstd-rs/blob/master/src/stream/raw.rs

Which just makes me realize this `zstd::stream::raw` is a 4th option: a very thin wrapper around the zstd_safe API, bringing some convenience.

**Comment by ebadta81** [comment]
> In particular, the pos indexes in InBuffer and OutBuffer mark the end of the data "processed" (read for InBuffer, written for OutBuffer) within the buffer itself (not within the entire file). If any data has been consumed like this, it doesn't need to be given again (but any data after pos still has not be consumed yet).

That's what I thought, thank you for confirming it.

Now it is working like a charm, there are only one issue left: I try to enable multithread encoding/decoding, and I got no error message, but it works only on one core.

Do you have any idea why is that?

This is in my Cargo.toml

```
zstd = { version = "0.11.2", features = ["zstdmt"] }
zstd-safe = { version = "5.0.2", features = ["zstdmt"] }
```

and my code for encoding:

```
	let mut cursor = Cursor::new(zstd_data);
	let mut encoder = Encoder::new(target, 22)?;
	encoder.multithread(7)?;
	io::copy(&mut cursor, &mut encoder)?;
	encoder.finish()?;
```


For decoding, I use _zstd_safe::DCtx_, but couldn't find anything I could add to set_parameter because DParameter does not have NbWorkers enum.

How can I enable multithread for zstd_safe::DCtx?

**Comment by gyscos** [comment]
Zstd only supports multithreaded compression, not decompression.

Usually decompression is fast enough that it's not an issue.
You can decompress different streams in parallel though.

**Comment by ebadta81** [comment]
Thank you Alexandre,

I did change it to multithread decompression, and realized, it is really not the DCtx, which is the bottleneck in my program.
I also realized that compression level 22 caused multiple problems: big memory usage, and no multithread compression.

I changed it to 18, and now everything is fine.


Thanks for all your help Alexandre!
