### ISSUE TITLE
zstd_safe: ZSTD_compressBegin and ZSTD_decompressBegin for usage with CompressBlock/DecompressBlock

### ISSUE THREAD

**Issue by sargarass** [gyscos/zstd-rs#293]
Hello, 

I'm trying to implement my own framing for Zstd with custom frame headers. For this purpose, I decided to use the `Block level API`.

According to the Zstd documentation for using `ZSTD_compressBlock`, the `ctx` should be initialized using `ZSTD_compressBegin`.
```
Block level API
Frame metadata cost is typically ~12 bytes, which can be non-negligible for very small blocks (< 100 bytes).
But users will have to take in charge needed metadata to regenerate data, such as compressed and content sizes.

    A few rules to respect :
    - Compressing and decompressing require a context structure
      + Use ZSTD_createCCtx() and ZSTD_createDCtx()
    - It is necessary to init context before starting
      + compression : any ZSTD_compressBegin*() variant, including with dictionary
      + decompression : any ZSTD_decompressBegin*() variant, including with dictionary
      + copyCCtx() and copyDCtx() can be used too
````

However, I could not find a corresponding method in the zstd_safe::CCtx. In its absence, I attempted the following code:
```
let mut ctx = zstd_safe::CCtx::try_create().expect("could not create context");

ctx.init(params.level as CompressionLevel)
        .map_err(zstd_safe::get_error_name)
        .expect("OK");

//  frame_size == 128 KiB
ctx.set_parameter(CParameter::MaxBlockSize(params.frame_size.as_bytes() as u32))
        .map_err(zstd_safe::get_error_name)
        .expect("block size is limited");

// encoded contains 50462 bytes        
ctx.compress_block(&mut output, encoded).map_err(zstd_safe::get_error_name).expect("compression failed");
```

Unfortunately, this resulted in the error: `compression failed: "Src size is incorrect"`.

Additionally, a wrapper for `ZSTD_decompressBegin` is also missing.

Would you consider reviewing a PR to support these features if I create one under an experimental feature flag?

**Comment by gyscos** [comment]
Hi, and thanks for the report!
Indeed, it seems that `ZSTD_compressBegin` is not currently wrapped, most likely because it's deprecated:

You can see in the original lib that these `ZSTD_compressBegin` and `ZSTD_decompressBegin` methods are deprecated:

https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L2890-L2902

> This API is deprecated, and will be removed in a future version
> [...]
> Please use the normal streaming API instead: ZSTD_compressStream2, and ZSTD_decompressStream

So is the block-level API:
https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L3050-L3062

> This API is deprecated in favor of the regular compression API.
>     This API is deprecated in favor of the regular compression API.
>    You can get the frame header down to 2 bytes by setting:
>      - ZSTD_c_format = ZSTD_f_zstd1_magicless
>      - ZSTD_c_contentSizeFlag = 0
>      - ZSTD_c_checksumFlag = 0
>      - ZSTD_c_dictIDFlag = 0

These correspond to:
* https://docs.rs/zstd-safe/latest/zstd_safe/enum.CParameter.html#variant.Format
* https://docs.rs/zstd-safe/latest/zstd_safe/enum.CParameter.html#variant.ContentSizeFlag
* https://docs.rs/zstd-safe/latest/zstd_safe/enum.CParameter.html#variant.ChecksumFlag
* https://docs.rs/zstd-safe/latest/zstd_safe/enum.CParameter.html#variant.DictIdFlag

I suppose we _could_ add wrappers to these deprecated `*Begin` methods, but since they may get removed in a future version, it may be a better idea to start using the supported API instead.

**Comment by sargarass** [comment]
Thank you for pointing out that those functions are deprecated and for the information on how to reduce the frame header to 2 bytes.

To create my own framing, I used `compress_stream2` and passed block-sized data with `ZSTD_EndDirective::ZSTD_e_flush` to generate exactly one ZSTD block. Since it flushes directly to the output and isn't stored internally, I could prefix it with my own block header. When I need to finish the frame, I use `ZSTD_EndDirective::ZSTD_e_end`, which also flushes to the output. This allows me to place a new custom frame header afterward.

Could you also point out other parameters, besides `DParameter::WindowLogMax`, that affect memory usage during decompression, if any?
