### ISSUE TITLE
Compress result is different from python-zstd library

### ISSUE THREAD

**Issue by WindSoilder** [gyscos/zstd-rs#296]
Given the following code:
```rust
use std::io::Cursor;
use zstd;

fn main() {
    let body = zstd::encode_all(Cursor::new("{}".as_bytes()), 3).unwrap();
    for x in body.iter() {
        print!("\\x{x:x?}");
    }
}
```
It outputs: `\x28\xb5\x2f\xfd\x0\x58\x11\x0\x0\x7b\x7d`

And here is python code(I'm using [python-zstd](https://github.com/sergey-dryabzhinsky/python-zstd) lib)
```python
import zstd
print(zstd.compress("{}"))
```
It outputs: `b'(\xb5/\xfd \x02\x11\x00\x00{}'`, which is the same to `b'\x28\xb5\x2f\xfd\x20\x02\x11\x00\x00\x7b\x7d'`.

There are two bytes differents in the middle of output.  (`\x0\x58` in rust and `\x20\x02` in python, I have confirmed that I'm using the same `ZSTD_version` which is 1.5.6

Not really sure is there any way to work around this?  Or is it an issue belongs to `zstd-rs`?

Here is the background behind the issue: https://github.com/sergey-dryabzhinsky/python-zstd/issues/100

**Comment by gyscos** [comment]
Hi, and thanks for the report!

There are several options during compression (you can see the [`CParameter`](https://docs.rs/zstd/latest/zstd/stream/raw/enum.CParameter.html) enum). To get bit-perfect reproducibility you'll want to make sure both python-zstd and this library use the same.

Looking at [`python-zstd`](https://github.com/sergey-dryabzhinsky/python-zstd/blob/master/src/python-zstd.c#L54) it looks like they directly use `ZSTD_compress2` rather than using the stream approach, and manually set the number of workers to the number of physical cores.
I think one difference is that `ZSTD_compress2` might include the content size in the header, which you could do with [`Encoder::set_pledged_src_size`](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.set_pledged_src_size).

Note that even though the output is not bit-perfect match for python-zstd's output, it should be be able to be decompressed (it's normal for multiple compressed strings to decompress to the same content).

For example, you can check that the zstd CLI can decode the rust output:

```
printf "\x28\xb5\x2f\xfd\x0\x58\x11\x0\x0\x7b\x7d" | zstdcat
{}
```

And python's output as well:

```
printf "\x28\xb5\x2f\xfd\x20\x02\x11\x00\x00\x7b\x7d" | zstdcat
{}
```

Now, I agree that `python-zstd` not being able to decompress the output from the rust compressor is unfortunate and probably a bug.

**Comment by WindSoilder** [comment]
Thank you!  Using [Encoder::set_pledged_src_size](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.set_pledged_src_size) is a good workaround for it :-)
