### ISSUE TITLE
Push-`Decoder`?

### ISSUE THREAD

**Issue by dpc** [gyscos/zstd-rs#34]
Currently `Decoder` is wrapping a reader, which is an interface that I would call "pull" (`Decoder` is pulling-in the data it needs). I have 3 other compression libraries in `rdedup` already and they are all wrapping writers on both compression and decompression ("push" - since the user is pushing the input data in). I'm adding `zstd`, and taking a reader instead of the writer is much less convenient, since it reverses the control.

**Comment by dpc** [comment]
Also, unless I missed something, the current interface introduces additional copying. I already to have data in `Vec<u8>`, and now I have to copy it over into `&mut [u8]` argument to `io:::Read::read`, just so `zstd` can use it, instead of `zstd` just use it directly from the buffer I gave it.

**Comment by dpc** [comment]
Related code: https://github.com/dpc/rdedup/commit/4c86f7121c3ceccbe2c3ed057944893ec4072b54

BTW. The speed and compression ratio improvements are very nice! :)

**Comment by gyscos** [comment]
Hi, and thanks for the report!

* A write-oriented decompressor is indeed not currently available, but I will consider one (just like a read-based compressor). I initially skipped them because they are much less often needed - people usually don't care *how much* compressed data is used, they care about the decompressed side, but if your framework expects such behaviour, I'll see how to make this work.

* I'm not sure I understand where the extra copy happens. The argument given to `io::Read::read` is the output buffer, so zstd only writes there (and it does so directly).

* If you're just compression/decompressing an entire frame at once, you can have a look at [`decode_all`](https://docs.rs/zstd/0.4.13/zstd/stream/fn.decode_all.html) and [`encode_all`](https://docs.rs/zstd/0.4.13/zstd/stream/fn.encode_all.html) (or [`copy_decode`](https://docs.rs/zstd/0.4.13/zstd/stream/fn.copy_decode.html) and [`copy_encode`](https://docs.rs/zstd/0.4.13/zstd/stream/fn.copy_encode.html) which send the data to any `Write`, including `Vec<u8>`).

**Comment by gyscos** [comment]
Finally got to write a more generic `Read`/`Write` framework.
The `zio2` branch should now provide both `read` and `write` implementations of `Encoder` and `Decoder`. Have a try! :)

**Comment by gyscos** [comment]
`Read` and `Write` implementations of both decoder and encoder have been up for a while now. Don't hesitate to re-open if you still have issues!
