### ISSUE TITLE
Support for --no-dictID

### ISSUE THREAD

**Issue by FauxFaux** [gyscos/zstd-rs#37]
Currently, I believe, there's no way to:
 * specify the dictionary ID for `zstd::Encoder::with_dictionary`.
 * omit the dictionary ID from the stream, as the `zstd --no-dictID` command-line option does.

I'm after the second; as currently I get an extra null byte in my output when using dictionaries; the messages are actually bigger than without a dictionary.

Please add them!

**Comment by gyscos** [comment]
Thanks for the input!

It seems that:
* The `dictID` can be specified with `ZSTD_cParameter::ZSTD_p_dictIDFlag`.
* `noDictIDFlag` is a parameter of `ZSTD_frameParameters`, which can be given:
    * in `ZSTD_compress_using_CDict_advanced` or `ZSTD_initCStream_using_CDict_advanced`
    * as part of `ZSTD_parameters`, in `ZSTD_compressed_advanced` or `ZSTD_initCStream_advanced`

The `zstd` crate itself relies on `zstd-safe`, so that's where these feature should first appear.

Regarding the first point, I think this is what #40 helps with?
Regarding the second point, it's part of the "advanced" APIs that I haven't ported to `zstd-safe` yet.

**Comment by FauxFaux** [comment]
I believe, but haven't tested, that you can `setParamters` `ZSTD_p_dictIDFlag` on an existing `cctx` and it will work. Hence working on `setParameters`.

Maybe some of the sensible options could be exposed as builder-like methods on context creation?

I didn't see a way to fiddle with the `cctx` inside a `cstream`, so it can't fit perfectly into the current API, unless I missed something.

**Comment by phiresky** [comment]
Another thing that would be useful is allowing creation and decoding of magic-less headers (https://github.com/facebook/zstd/issues/591 https://github.com/facebook/zstd/pull/1080 ). I'm not sure if this is done with the same API as the dictid setting would be so I'm not sure if it's worth having as a separate issue.

**Comment by phiresky** [comment]
I've opened a PR here #98 to fix both dictid as well as magic header removal.
